name: interchange-regression-testing

channels:
  - conda-forge
  - openeye

dependencies:
    # Core
  - python
  - pip

  - click
  - rich

  - pydantic
  - numpy
  - pyyaml

  - openmm
  - openeye-toolkits

  - deepdiff
  - xmltodict

  - openff-toolkit =>0.10.4
  - openff-interchange-base
