name: interchange-regression-testing

channels:
  - conda-forge
  - openeye

dependencies:
    # Core
  - python =3.9
  - pip

  - click
  - rich

  - pydantic
  - numpy
  - pyyaml

  - openmm
  - openeye-toolkits

  - deepdiff
  - xmltodict

  - openff-toolkit-base =0.10.6
  - openff-interchange-base
